services:
  mongo:
    image: mongo:8.2
    volumes:
      - ./.mongo/data:/data/db
      - ./.mongo/config:/data/configdb
    ports:
      - "27017:27017"
    command: [ "mongod", "--port", "27017", "--bind_ip", "0.0.0.0", "--dbpath", "/data/db", "--replSet", "rs0" ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
  rabbitmq:
    image: rabbitmq:4.2-management
    volumes:
      - ./.rabbitmq/:/var/lib/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"
